const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const state = { token: localStorage.getItem('gt_token'), user: null, view: 'dashboard', trips: [], cities: [], currentTrip: null, month: new Date().toISOString().slice(0,7) };
const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0);
const fmtDate = d => d ? new Date(`${d}T00:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}) : '';
const esc = s => String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
async function api(url, options={}){
  const opts={...options,headers:{...(options.headers||{})}};
  if(state.token) opts.headers.Authorization=`Bearer ${state.token}`;
  if(opts.body && !(opts.body instanceof FormData)){opts.headers['Content-Type']='application/json';opts.body=JSON.stringify(opts.body)}
  const r=await fetch(url,opts);let data={};try{data=await r.json()}catch{}
  if(!r.ok) throw new Error(data.error||`Request failed (${r.status})`);return data;
}
function initials(u=state.user){return ((u?.first_name||u?.firstName||'G')[0]+(u?.last_name||u?.lastName||'T')[0]).toUpperCase()}

function showAuth(mode='login'){
  $('#app').classList.add('hidden');$('#authApp').classList.remove('hidden');
  $('#authApp').innerHTML=`<div class="auth-card">
    <div class="auth-brand"><div class="brand"><span class="brand-mark">G</span><span>GlobeTrotter</span></div><h1>Plan the journey.<br>Live the story.</h1><p>Build multi-city trips, discover activities, track every rupee and share your itinerary with your travel community.</p><div class="pill orange" style="width:max-content">Personalized travel planning</div></div>
    <div class="auth-form"><div class="auth-tabs"><button id="loginTab" class="${mode==='login'?'active':''}">Login</button><button id="registerTab" class="${mode==='register'?'active':''}">Create account</button></div><div id="authForm"></div></div></div>`;
  $('#loginTab').onclick=()=>showAuth('login');$('#registerTab').onclick=()=>showAuth('register');
  if(mode==='login') renderLogin(); else renderRegister();
}
function renderLogin(){
  $('#authForm').innerHTML=`<h2>Welcome back</h2><p>Access your trips and continue planning.</p><form id="loginForm"><div class="field"><label>Username or email</label><input class="input" name="usernameOrEmail" required autocomplete="username"></div><div class="field" style="margin-top:12px"><label>Password</label><input class="input" name="password" type="password" required autocomplete="current-password"></div><div id="authMsg" class="auth-message"></div><button class="btn primary" style="width:100%;margin-top:12px">Login</button><p class="muted" style="margin-top:16px;font-size:11px">Demo admin: admin@globetrotter.local / Admin@123</p></form>`;
  $('#loginForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const d=await api('/api/auth/login',{method:'POST',body});state.token=d.token;state.user=d.user;localStorage.setItem('gt_token',state.token);startApp()}catch(err){$('#authMsg').textContent=err.message}};
}
function renderRegister(){
  $('#authForm').innerHTML=`<h2>Create your account</h2><p>Start building your personalized travel plans.</p><form id="registerForm"><div class="form-grid"><div class="field"><label>Username</label><input class="input" name="username" required></div><div class="field"><label>Email</label><input class="input" name="email" type="email" required></div><div class="field"><label>First name</label><input class="input" name="firstName" required></div><div class="field"><label>Last name</label><input class="input" name="lastName" required></div><div class="field"><label>Password</label><input class="input" name="password" type="password" minlength="6" required></div><div class="field"><label>Phone</label><input class="input" name="phone"></div><div class="field"><label>City</label><input class="input" name="city"></div><div class="field"><label>Country</label><input class="input" name="country"></div><div class="field full"><label>About you</label><textarea class="textarea" name="bio" placeholder="Travel style, interests, etc."></textarea></div></div><div id="authMsg" class="auth-message"></div><button class="btn primary" style="width:100%;margin-top:12px">Create account</button></form>`;
  $('#registerForm').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));try{const d=await api('/api/auth/register',{method:'POST',body});state.token=d.token;state.user=d.user;localStorage.setItem('gt_token',state.token);startApp()}catch(err){$('#authMsg').textContent=err.message}};
}

async function startApp(){
  try{const d=await api('/api/auth/me');state.user=d.user}catch{state.token=null;localStorage.removeItem('gt_token');return showAuth('login')}
  $('#authApp').classList.add('hidden');$('#app').classList.remove('hidden');
  $('#profileTop').textContent=initials();$('.admin-link').classList.toggle('hidden',state.user.role!=='admin');
  bindGlobal();navigate(state.view||'dashboard');
}
function bindGlobal(){
  $$('#mainNav [data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
  $$('.icon-btn[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
  $('#profileTop').onclick=()=>navigate('profile');
  $('#logoutBtn').onclick=()=>{state.token=null;state.user=null;localStorage.removeItem('gt_token');showAuth('login')};
}
function navigate(view){state.view=view;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:['YOUR TRAVEL HUB','Dashboard'],trips:['YOUR JOURNEYS','My Trips'],create:['BUILD SOMETHING GREAT','Plan New Trip'],search:['DISCOVER','Explore Cities & Activities'],calendar:['YOUR TIMELINE','Calendar'],community:['TRAVEL TOGETHER','Community'],profile:['ACCOUNT','Profile & Settings'],admin:['CONTROL CENTER','Admin Analytics']};$('#pageEyebrow').textContent=titles[view]?.[0]||'GLOBETROTTER';$('#pageTitle').textContent=titles[view]?.[1]||'GlobeTrotter';renderView(view)}

async function renderView(view){
  const c=$('#content');c.innerHTML='<div class="loading">Loading...</div>';
  try{if(view==='dashboard')return await dashboard(c);if(view==='trips')return await trips(c);if(view==='create')return createTrip(c);if(view==='search')return await search(c);if(view==='calendar')return await calendar(c);if(view==='community')return await community(c);if(view==='profile')return await profile(c);if(view==='admin')return await admin(c);}
  catch(e){c.innerHTML=`<div class="card danger">${esc(e.message)}</div>`}
}

async function loadTrips(){state.trips=(await api('/api/trips')).trips;return state.trips}
async function loadCities(q=''){state.cities=(await api('/api/cities?q='+encodeURIComponent(q))).cities;return state.cities}

async function dashboard(c){
  const trips=await loadTrips(), cities=await loadCities();
  const upcoming=trips.filter(t=>t.end_date>=new Date().toISOString().slice(0,10));
  c.innerHTML=`<div class="hero"><div><span class="pill orange">Your next adventure starts here</span><h2>Where will you go next, ${esc(state.user.first_name)}?</h2><p>Turn destinations into a day-by-day plan. Add stops, activities and expenses without losing sight of your budget.</p><div class="hero-actions"><button class="btn primary" data-view="create">＋ Plan a new trip</button><button class="btn dark" data-view="search">Explore destinations</button></div></div></div>
  <div class="grid grid-4" style="margin-top:20px"><div class="card stat"><div><div class="label">Total trips</div><div class="value">${trips.length}</div></div><div class="stat-icon">✈</div></div><div class="card stat"><div><div class="label">Upcoming</div><div class="value">${upcoming.length}</div></div><div class="stat-icon">◷</div></div><div class="card stat"><div><div class="label">Planned stops</div><div class="value">${trips.reduce((a,b)=>a+Number(b.stop_count),0)}</div></div><div class="stat-icon">⌖</div></div><div class="card stat"><div><div class="label">Activities</div><div class="value">${trips.reduce((a,b)=>a+Number(b.activity_count),0)}</div></div><div class="stat-icon">★</div></div></div>
  <div class="section-head"><h3>Top destinations</h3><button class="btn small" data-view="search">See all</button></div><div class="destination-row">${cities.slice(0,6).map(cityCard).join('')}</div>
  <div class="section-head"><h3>Your recent trips</h3><button class="btn small" data-view="trips">Manage trips</button></div><div class="grid grid-3">${trips.slice(0,3).map(tripCard).join('')||`<div class="card empty" style="grid-column:1/-1">No trips yet. Create your first itinerary.</div>`}</div>`;
  wireDataViews(c);$$('.destination-save',c).forEach(b=>b.onclick=async()=>{try{await api('/api/saved-destinations/'+b.dataset.id,{method:'POST'});toast('Destination saved.')}catch(e){toast(e.message)}});
}
function cityCard(c){return `<div class="destination"><div class="destination-img" style="background-image:url('${esc(c.image_url)}')"></div><div class="destination-body"><b>${esc(c.name)}</b><span>${esc(c.country)} · ${esc(c.region)}</span><button class="btn small destination-save" data-id="${c.id}" style="margin-top:9px">Save</button></div></div>`}
function tripCard(t){return `<div class="card trip-card"><div class="trip-cover" style="${t.cover_photo||''?`background-image:url('${esc(t.cover_photo)}')`:''}"><span class="badge">${t.is_public?'PUBLIC':'PRIVATE'}</span></div><div class="trip-body"><h4>${esc(t.name)}</h4><div class="trip-meta"><span>${fmtDate(t.start_date)} – ${fmtDate(t.end_date)}</span><span>· ${t.stop_count} stops</span><span>· ${money(t.total_cost)}</span></div><div class="trip-actions"><button class="btn small primary view-trip" data-id="${t.id}">View itinerary</button><button class="btn small edit-trip" data-id="${t.id}">Edit</button></div></div></div>`}
function wireTripCards(root){$$('.view-trip',root).forEach(b=>b.onclick=()=>openTrip(b.dataset.id));$$('.edit-trip',root).forEach(b=>b.onclick=()=>editTrip(b.dataset.id))}
function wireDataViews(root){$$('[data-view]',root).forEach(b=>b.onclick=()=>navigate(b.dataset.view));wireTripCards(root)}

async function trips(c){const list=await loadTrips();c.innerHTML=`<div class="toolbar"><input id="tripFilter" class="input" placeholder="Search your trips..."><button class="btn primary" data-view="create">＋ Plan new trip</button></div><div id="tripList" class="grid grid-3" style="margin-top:18px">${list.map(tripCard).join('')||`<div class="card empty" style="grid-column:1/-1">No trips found. Create your first trip.</div>`}</div>`;$('#tripFilter').oninput=e=>{const q=e.target.value.toLowerCase();$('#tripList').innerHTML=list.filter(t=>t.name.toLowerCase().includes(q)).map(tripCard).join('')||'<div class="card empty" style="grid-column:1/-1">No matching trips.</div>';wireTripCards($('#tripList'))};wireDataViews(c)}

function createTrip(c, existing=null){
  c.innerHTML=`<div class="card"><div class="section-head" style="margin-top:0"><div><h3>${existing?'Edit trip':'Create a new trip'}</h3><div class="muted">Start with the basic details. You can add cities and activities next.</div></div></div><form id="tripForm"><div class="form-grid"><div class="field"><label>Trip name</label><input class="input" name="name" required value="${esc(existing?.name||'')}"></div><div class="field"><label>Budget (₹)</label><input class="input" name="budget" type="number" min="0" value="${existing?.budget||0}"></div><div class="field"><label>Start date</label><input class="input" name="startDate" type="date" required value="${existing?.start_date||''}"></div><div class="field"><label>End date</label><input class="input" name="endDate" type="date" required value="${existing?.end_date||''}"></div><div class="field full"><label>Description</label><textarea class="textarea" name="description" placeholder="What is this trip about?">${esc(existing?.description||'')}</textarea></div><div class="field"><label>Cover photo URL (optional)</label><input class="input" name="coverPhoto" value="${esc(existing?.cover_photo||'')}" placeholder="https://..."></div><div class="field" style="align-self:end"><label style="display:flex;gap:8px;align-items:center"><input name="isPublic" type="checkbox" ${existing?.is_public?'checked':''}> Make this itinerary public</label></div></div><div id="formMsg" class="auth-message"></div><div class="toolbar" style="margin-top:18px"><button type="submit" class="btn primary">${existing?'Save changes':'Create trip'}</button><button type="button" class="btn" data-view="trips">Cancel</button></div></form></div>`;
  wireDataViews(c);$('#tripForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target), body=Object.fromEntries(f);body.isPublic=f.has('isPublic');try{if(existing){await api('/api/trips/'+existing.id,{method:'PUT',body});toast('Trip updated');navigate('trips')}else{const d=await api('/api/trips',{method:'POST',body});toast('Trip created');openTrip(d.trip.id)}}catch(err){$('#formMsg').textContent=err.message}};
}
async function editTrip(id){const t=(await api('/api/trips/'+id)).trip;state.view='create';navigate('create');setTimeout(()=>createTrip($('#content'),t),0)}

async function openTrip(id){const d=await api('/api/trips/'+id);state.currentTrip=d.trip;renderItinerary(d.trip)}
function renderItinerary(t){state.view='itinerary';$$('.nav-item').forEach(b=>b.classList.remove('active'));$('#pageEyebrow').textContent='TRIP BUILDER';$('#pageTitle').textContent=t.name;const c=$('#content');
  const days=dateList(t.start_date,t.end_date);const byDate={};days.forEach(d=>byDate[d]=[]);t.activities.forEach(a=>(byDate[a.activity_date] ||= []).push(a));
  c.innerHTML=`<div class="toolbar"><button class="btn" id="backTrips">← My Trips</button><button class="btn" id="addStop">＋ Add stop</button><button class="btn" id="addActivity">＋ Add activity</button><button class="btn" id="addExpense">＋ Expense</button><button class="btn" id="budgetBtn">₹ Budget</button><button class="btn" id="shareBtn">${t.is_public?'🔗 Share':'🌐 Make public'}</button><button class="btn danger" id="deleteTrip">Delete</button></div><div class="split" style="margin-top:18px"><div><div class="card"><div class="section-head" style="margin-top:0"><div><h3>Itinerary timeline</h3><div class="muted">${fmtDate(t.start_date)} – ${fmtDate(t.end_date)} · ${t.stops.length} stops</div></div><span class="pill ${t.total_cost>t.budget&&t.budget?'orange':'green'}">${money(t.total_cost)} / ${money(t.budget)} budget</span></div>${days.map(d=>`<div class="itinerary-day"><div class="day-head"><span class="day-title">${new Date(d+'T00:00:00').toLocaleDateString('en-IN',{weekday:'short',day:'numeric',month:'short'})}</span><span class="muted">${esc(t.stops.find(s=>d>=s.start_date&&d<=s.end_date)?.city_name||'Travel day')}</span></div>${(byDate[d]||[]).map(a=>`<div class="activity-line"><div class="time">${esc(a.start_time||'Anytime')}</div><div><div class="activity-name">${esc(a.activity_name)} <span class="pill">${esc(a.category)}</span></div><div class="activity-desc">${esc(a.notes||a.description||'')}</div></div><div><div class="cost">${money(a.estimated_cost)}</div><button class="btn small delete-act" data-id="${a.id}" style="margin-top:5px">Remove</button></div></div>`).join('')||'<div class="muted" style="padding:13px 0;font-size:12px">No activity planned.</div>'}</div>`).join('')}</div></div><div><div class="card"><div class="section-head" style="margin-top:0"><h3>Stops</h3></div>${t.stops.map(s=>`<div class="card" style="padding:12px;margin-bottom:10px;box-shadow:none"><b>${esc(s.city_name)}</b><div class="muted" style="font-size:11px;margin:4px 0">${fmtDate(s.start_date)} – ${fmtDate(s.end_date)}</div><button class="btn small danger delete-stop" data-id="${s.id}">Remove</button></div>`).join('')||'<div class="empty">No stops yet.</div>'}</div><div class="card" style="margin-top:20px"><h3 style="margin-top:0">Trip summary</h3><div class="stat"><span class="muted">Activities</span><b>${t.activities.length}</b></div><div class="stat" style="margin-top:10px"><span class="muted">Spent / estimated</span><b>${money(t.total_cost)}</b></div><div class="stat" style="margin-top:10px"><span class="muted">Remaining</span><b class="${t.total_cost>t.budget&&t.budget?'':'success'}">${money(Number(t.budget)-Number(t.total_cost))}</b></div><div style="margin-top:15px" class="progress"><span style="width:${t.budget?Math.min(100,t.total_cost/t.budget*100):0}%"></span></div></div></div></div>`;
  $('#backTrips').onclick=()=>navigate('trips');$('#addStop').onclick=()=>stopModal(t);$('#addActivity').onclick=()=>activityModal(t);$('#addExpense').onclick=()=>expenseModal(t);$('#budgetBtn').onclick=()=>budgetView(t);$('#shareBtn').onclick=()=>shareTrip(t);$('#deleteTrip').onclick=async()=>{if(confirm('Delete this trip permanently?')){await api('/api/trips/'+t.id,{method:'DELETE'});toast('Trip deleted');navigate('trips')}};$$('.delete-stop').forEach(b=>b.onclick=async()=>{if(confirm('Remove this stop and its activities?')){await api('/api/stops/'+b.dataset.id,{method:'DELETE'});openTrip(t.id)}});$$('.delete-act').forEach(b=>b.onclick=async()=>{if(confirm('Remove this activity?')){await api('/api/trip-activities/'+b.dataset.id,{method:'DELETE'});openTrip(t.id)}});
}
function dateList(start,end){const out=[];let d=new Date(start+'T00:00:00'),b=new Date(end+'T00:00:00');while(d<=b){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out}
function modal(title,html){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3 style="margin:0">${title}</h3><button class="close">×</button></div>${html}</div>`;document.body.appendChild(wrap);$('.close',wrap).onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};return wrap}
async function stopModal(t){const cities=await loadCities();const m=modal('Add a city stop',`<form id="stopForm"><div class="form-grid"><div class="field full"><label>City</label><select class="select" name="cityId" required>${cities.map(c=>`<option value="${c.id}">${esc(c.name)}, ${esc(c.country)}</option>`).join('')}</select></div><div class="field"><label>Start</label><input class="input" name="startDate" type="date" min="${t.start_date}" max="${t.end_date}" value="${t.start_date}" required></div><div class="field"><label>End</label><input class="input" name="endDate" type="date" min="${t.start_date}" max="${t.end_date}" value="${t.end_date}" required></div></div><button class="btn primary" style="margin-top:15px">Add stop</button></form>`);$('#stopForm',m).onsubmit=async e=>{e.preventDefault();try{await api('/api/trips/'+t.id+'/stops',{method:'POST',body:Object.fromEntries(new FormData(e.target))});m.remove();toast('Stop added');openTrip(t.id)}catch(err){toast(err.message)}}}
async function activityModal(t){if(!t.stops.length)return toast('Add a city stop first.');const m=modal('Add an activity',`<form id="activityForm"><div class="form-grid"><div class="field full"><label>Stop</label><select class="select" name="stopId" id="stopSelect">${t.stops.map(s=>`<option value="${s.id}">${esc(s.city_name)} · ${fmtDate(s.start_date)} – ${fmtDate(s.end_date)}</option>`).join('')}</select></div><div class="field full"><label>Activity</label><select class="select" name="activityId" id="activitySelect"></select></div><div class="field"><label>Date</label><input class="input" id="activityDate" name="activityDate" type="date" required></div><div class="field"><label>Start time</label><input class="input" name="startTime" type="time"></div><div class="field"><label>Estimated cost (₹)</label><input class="input" name="estimatedCost" type="number" min="0"></div><div class="field"><label>Notes</label><input class="input" name="notes"></div></div><button class="btn primary" style="margin-top:15px">Add activity</button></form>`);async function fill(){const s=t.stops.find(x=>x.id==$('#stopSelect',m).value);const a=(await api('/api/cities/'+s.city_id+'/activities')).activities;$('#activitySelect',m).innerHTML=a.map(x=>`<option value="${x.id}" data-cost="${x.estimated_cost}">${esc(x.name)} · ${money(x.estimated_cost)}</option>`).join('');$('#activityDate',m).min=s.start_date;$('#activityDate',m).max=s.end_date;$('#activityDate',m).value=s.start_date;$('#activitySelect',m).onchange=()=>$('#activityForm input[name=estimatedCost]',m).value=$('#activitySelect option:checked',m)?.dataset.cost||0}await fill();$('#stopSelect',m).onchange=fill;$('#activityForm',m).onsubmit=async e=>{e.preventDefault();try{await api('/api/trips/'+t.id+'/activities',{method:'POST',body:Object.fromEntries(new FormData(e.target))});m.remove();toast('Activity added');openTrip(t.id)}catch(err){toast(err.message)}}}
function expenseModal(t){const m=modal('Add expense',`<form id="expenseForm"><div class="form-grid"><div class="field"><label>Category</label><select class="select" name="category"><option>Transport</option><option>Stay</option><option>Meals</option><option>Activities</option><option>Other</option></select></div><div class="field"><label>Amount (₹)</label><input class="input" name="amount" type="number" min="0" required></div><div class="field full"><label>Description</label><input class="input" name="description" required placeholder="Hotel, train ticket, dinner..."></div><div class="field"><label>Date</label><input class="input" name="expenseDate" type="date" value="${t.start_date}" required></div></div><button class="btn primary" style="margin-top:15px">Save expense</button></form>`);$('#expenseForm',m).onsubmit=async e=>{e.preventDefault();try{await api('/api/trips/'+t.id+'/expenses',{method:'POST',body:Object.fromEntries(new FormData(e.target))});m.remove();toast('Expense added');openTrip(t.id)}catch(err){toast(err.message)}}}
async function shareTrip(t){const makePublic=!t.is_public;try{const d=await api('/api/trips/'+t.id+'/public',{method:'POST',body:{isPublic:makePublic}});if(makePublic){const url=location.origin+'/share.html?token='+d.token;navigator.clipboard?.writeText(url);toast('Public link copied: '+url)}else toast('Trip is private now');openTrip(t.id)}catch(e){toast(e.message)}}

async function budgetView(t){const d=await api('/api/trips/'+t.id+'/budget');const max=Math.max(...d.categories.map(x=>x.amount),1);const m=modal('Budget & cost breakdown',`<div class="grid grid-4"><div class="card stat"><div><div class="label">Budget</div><div class="value">${money(d.budget)}</div></div></div><div class="card stat"><div><div class="label">Estimated total</div><div class="value">${money(d.total)}</div></div></div><div class="card stat"><div><div class="label">Remaining</div><div class="value">${money(d.remaining)}</div></div></div><div class="card stat"><div><div class="label">Average/day</div><div class="value">${money(d.averagePerDay)}</div></div></div></div><div class="card" style="margin-top:18px"><h4>Cost by category</h4>${d.categories.map(x=>`<div class="bar-row"><span>${esc(x.category)}</span><div class="bar"><span style="width:${x.amount/max*100}%"></span></div><b>${money(x.amount)}</b></div>`).join('')||'<div class="empty">No costs yet.</div>'}</div>${d.remaining<0&&d.budget?'<div class="notice danger" style="margin-top:15px">You are over budget. Consider removing or replacing expensive activities.</div>':''}`);}

async function search(c){
  c.innerHTML=`<div class="card"><div class="toolbar"><input id="exploreQ" class="input" placeholder="Search cities, countries or activities..."><select id="exploreType" class="select" style="max-width:160px"><option value="cities">Cities</option><option value="activities">Activities</option></select><select id="exploreSort" class="select" style="max-width:160px"><option value="popular">Popular</option><option value="cost">Lowest cost</option><option value="name">Name</option></select><button id="exploreGo" class="btn primary">Search</button></div></div><div id="exploreResults" style="margin-top:18px"></div>`;
  const go=async()=>{
    const q=$('#exploreQ').value;
    const type=$('#exploreType').value;
    const sort=$('#exploreSort').value;
    const r=$('#exploreResults');
    r.innerHTML='<div class="loading">Searching...</div>';
    if(type==='cities'){
      const d=await api('/api/cities?q='+encodeURIComponent(q)+'&sort='+sort);
      r.innerHTML=d.cities.map(x=>`<div class="card" style="margin-bottom:12px"><div class="result-row"><div class="result-img" style="background-image:url('${esc(x.image_url)}')"></div><div class="result-main"><h4>${esc(x.name)}, ${esc(x.country)}</h4><div><span class="pill orange">${esc(x.region)}</span> <span class="pill">Cost index ${x.cost_index}</span> <span class="pill">${x.popularity}% popularity</span></div><p style="margin-top:7px">${esc(x.description)}</p></div><button class="btn primary small" data-city="${x.id}">Save destination</button></div></div>`).join('') || '<div class="empty">No cities found.</div>';
      $$('[data-city]',r).forEach(b=>b.onclick=async()=>{try{await api('/api/saved-destinations/'+b.dataset.city,{method:'POST'});toast('Destination saved')}catch(e){toast(e.message)}});
    }else{
      const d=await api('/api/activities?q='+encodeURIComponent(q));
      r.innerHTML=d.activities.map(x=>`<div class="card" style="margin-bottom:12px"><div class="result-row"><div class="result-img" style="background-image:url('${esc(x.image_url||'')}')"></div><div class="result-main"><h4>${esc(x.name)}</h4><div><span class="pill orange">${esc(x.category)}</span> <span class="pill">${esc(x.city_name)}, ${esc(x.country)}</span> <span class="pill">${money(x.estimated_cost)}</span></div><p style="margin-top:7px">${esc(x.description)} · ${x.duration_hours} hrs</p></div></div></div>`).join('') || '<div class="empty">No activities found.</div>';
    }
  };
  $('#exploreGo').onclick=go;
  $('#exploreQ').onkeydown=e=>{if(e.key==='Enter')go()};
  go();
}

async function calendar(c){const d=await api('/api/calendar?month='+state.month);const [y,mo]=state.month.split('-').map(Number);const first=new Date(y,mo-1,1),daysIn=new Date(y,mo,0).getDate(),start=first.getDay();const heads=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];let cells='';for(let i=0;i<start;i++)cells+='<div class="cal-day muted-day"></div>';for(let day=1;day<=daysIn;day++){const date=`${state.month}-${String(day).padStart(2,'0')}`;const items=d.items.filter(x=>x.date===date);cells+=`<div class="cal-day"><div class="date">${day}</div>${items.map(x=>`<div class="cal-item" title="${esc(x.activity_name)}">${esc(x.activity_name)}</div>`).join('')}</div>`}c.innerHTML=`<div class="card"><div class="section-head" style="margin-top:0"><div><h3>Calendar view</h3><div class="muted">Your activity timeline and trip dates.</div></div><div class="toolbar"><button class="btn" id="prevMonth">←</button><b>${first.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</b><button class="btn" id="nextMonth">→</button></div></div><div class="calendar">${heads.map(h=>`<div class="cal-head">${h}</div>`).join('')}${cells}</div></div><div class="section-head"><h3>Trips around this month</h3></div><div class="grid grid-3">${d.trips.map(t=>tripCard(t)).join('')||'<div class="card empty" style="grid-column:1/-1">No trips in this month.</div>'}</div>`;$('#prevMonth').onclick=()=>{state.month=shiftMonth(state.month,-1);calendar(c)};$('#nextMonth').onclick=()=>{state.month=shiftMonth(state.month,1);calendar(c)};wireTripCards(c)}
function shiftMonth(m,delta){const [y,mo]=m.split('-').map(Number);const d=new Date(y,mo-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}

async function community(c){const d=await api('/api/community');c.innerHTML=`<div class="hero" style="min-height:190px"><div><span class="pill orange">Community</span><h2>Get inspired by real itineraries.</h2><p>Browse public trips, copy one into your account and customize it for yourself.</p></div></div><div class="section-head"><h3>Public trips</h3></div><div class="grid grid-3">${d.trips.map(t=>`<div class="card trip-card"><div class="trip-cover" style="${t.cover_photo?`background-image:url('${esc(t.cover_photo)}')`:''}"></div><div class="trip-body"><h4>${esc(t.name)}</h4><div class="trip-meta">by @${esc(t.username)} · ${t.stop_count} stops · ${money(t.total_cost)}</div><p class="muted" style="font-size:12px;line-height:1.5">${esc(t.description||'A shared GlobeTrotter itinerary.')}</p><div class="trip-actions"><button class="btn small" data-share="${esc(t.share_token)}">View</button><button class="btn small primary" data-copy="${t.id}">Copy trip</button></div></div></div>`).join('')||'<div class="card empty" style="grid-column:1/-1">No public trips yet. Make one of yours public!</div>'}</div>`;$$('[data-share]',c).forEach(b=>b.onclick=()=>window.open('/share.html?token='+b.dataset.share,'_blank'));$$('[data-copy]',c).forEach(b=>b.onclick=async()=>{try{const x=await api('/api/trips/'+b.dataset.copy+'/copy',{method:'POST'});toast('Trip copied to your account');openTrip(x.trip.id)}catch(e){toast(e.message)}})}

async function profile(c){const d=await api('/api/profile'),u=d.user;c.innerHTML=`<div class="card"><div class="profile-head"><div class="profile-avatar" style="${u.photo_url?`background-image:url('${esc(u.photo_url)}');font-size:0`:''}">${initials(u)}</div><div><h2 style="margin:0">${esc(u.first_name)} ${esc(u.last_name)}</h2><div class="muted">@${esc(u.username)} · ${esc(u.email)}</div><span class="pill" style="margin-top:7px">${esc(u.role)}</span></div></div></div><div class="grid grid-2" style="margin-top:20px"><div class="card"><h3 style="margin-top:0">Profile details</h3><form id="profileForm"><div class="form-grid"><div class="field"><label>First name</label><input class="input" name="firstName" value="${esc(u.first_name)}"></div><div class="field"><label>Last name</label><input class="input" name="lastName" value="${esc(u.last_name)}"></div><div class="field"><label>Email</label><input class="input" name="email" type="email" value="${esc(u.email)}"></div><div class="field"><label>Phone</label><input class="input" name="phone" value="${esc(u.phone)}"></div><div class="field"><label>City</label><input class="input" name="city" value="${esc(u.city)}"></div><div class="field"><label>Country</label><input class="input" name="country" value="${esc(u.country)}"></div><div class="field"><label>Language</label><select class="select" name="language"><option ${u.language==='English'?'selected':''}>English</option><option ${u.language==='Hindi'?'selected':''}>Hindi</option><option ${u.language==='Gujarati'?'selected':''}>Gujarati</option></select></div><div class="field"><label>Photo URL</label><input class="input" name="photoUrl" value="${esc(u.photo_url)}"></div><div class="field full"><label>Bio</label><textarea class="textarea" name="bio">${esc(u.bio)}</textarea></div></div><button class="btn primary" style="margin-top:15px">Save profile</button></form><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><h4>Upload profile photo</h4><form id="photoForm" enctype="multipart/form-data"><input class="input" type="file" name="photo" accept="image/*" required><button class="btn" style="margin-top:10px">Upload</button></form></div><div class="card"><h3 style="margin-top:0">Saved destinations</h3>${d.saved.map(x=>`<div class="result-row" style="padding:10px 0;border-bottom:1px solid var(--line)"><div class="result-img" style="background-image:url('${esc(x.image_url)}')"></div><div class="result-main"><b>${esc(x.name)}</b><p>${esc(x.country)} · ${esc(x.region)}</p></div><button class="btn small" data-unsave="${x.id}">Remove</button></div>`).join('')||'<div class="empty">No saved destinations yet.</div>'}<div class="notice danger" style="margin-top:25px"><b>Danger zone</b><div style="margin-top:5px">Delete your account and all your trips permanently.</div><button id="deleteAccount" class="btn danger small" style="margin-top:10px">Delete account</button></div></div></div>`;
  $('#profileForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/profile',{method:'PUT',body:Object.fromEntries(new FormData(e.target))});state.user=d.user;$('#profileTop').textContent=initials();toast('Profile updated')}catch(e){toast(e.message)}};
  $('#photoForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/profile/photo',{method:'POST',body:new FormData(e.target)});toast('Photo uploaded');profile(c)}catch(e){toast(e.message)}};
  $$('[data-unsave]',c).forEach(b=>b.onclick=async()=>{await api('/api/saved-destinations/'+b.dataset.unsave,{method:'DELETE'});profile(c)});
  $('#deleteAccount').onclick=async()=>{if(confirm('Delete your account and all data? This cannot be undone.')){await api('/api/profile',{method:'DELETE'});state.token=null;localStorage.removeItem('gt_token');showAuth('login')}};
}

async function admin(c){if(state.user.role!=='admin')return c.innerHTML='<div class="card danger">Admin access required.</div>';const d=await api('/api/admin/stats');c.innerHTML=`<div class="grid grid-4"><div class="card stat"><div><div class="label">Users</div><div class="value">${d.stats.users}</div></div><div class="stat-icon">●</div></div><div class="card stat"><div><div class="label">Trips</div><div class="value">${d.stats.trips}</div></div><div class="stat-icon">✈</div></div><div class="card stat"><div><div class="label">Public trips</div><div class="value">${d.stats.publicTrips}</div></div><div class="stat-icon">◎</div></div><div class="card stat"><div><div class="label">Activities planned</div><div class="value">${d.stats.activities}</div></div><div class="stat-icon">★</div></div></div><div class="grid grid-2" style="margin-top:20px"><div class="card"><h3 style="margin-top:0">Popular cities</h3>${d.topCities.map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar"><span style="width:${Math.min(100,x.visits*20)}%"></span></div><b>${x.visits}</b></div>`).join('')||'<div class="empty">No data.</div>'}</div><div class="card"><h3 style="margin-top:0">Popular activities</h3>${d.topActivities.map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar"><span style="width:${Math.min(100,x.uses*20)}%"></span></div><b>${x.uses}</b></div>`).join('')||'<div class="empty">No data.</div>'}</div></div><div class="card" style="margin-top:20px"><div class="section-head" style="margin-top:0"><h3>User management</h3><span class="muted">Recent accounts</span></div><table class="table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Created</th><th></th></tr></thead><tbody>${d.users.map(u=>`<tr><td>@${esc(u.username)}<br><span class="muted">${esc(u.first_name)} ${esc(u.last_name)}</span></td><td>${esc(u.email)}</td><td>${esc(u.role)}</td><td>${fmtDate(u.created_at.slice(0,10))}</td><td>${u.id!==state.user.id?`<button class="btn danger small" data-deluser="${u.id}">Delete</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;$$('[data-deluser]',c).forEach(b=>b.onclick=async()=>{if(confirm('Delete this user and all their trips?')){await api('/api/admin/users/'+b.dataset.deluser,{method:'DELETE'});toast('User deleted');admin(c)}})}

// Initial boot
if(state.token) startApp(); else showAuth('login');
